### ISSUE TITLE
Allow multiple sensors

### ISSUE THREAD

**Issue by gavinmacaulay** [ices-eg/wg_WGFAST#13]
Split from issue #2 

By @cyrilleponcelet: In my systems I could have several position and attitude sensors connected, I would proposed a way to organize those description in order to support those type of multi sensors data.

@cyrilleponcelet will create a pull request.

**Comment by cyrilleponcelet** [comment]
Merge request will be submitted after issues #12 resolution

**Comment by cyrilleponcelet** [comment]
Hi Gavin, before I start to make some pull request, for this subject I need to define new subgroups (one per equipment, let's say we have two positionning system, you will have two subgroups).
Do you want me to create a new adoc file per subgroup or put everything in the platform adoc file ? By the end I think we will create new file but it might be harder to follow the changes with the pull request if I do that right now.
Tell me what you prefer

**Comment by gavinmacaulay** [comment]
I don't have a strong preference, so whatever suits you is fine.

**Comment by gavinmacaulay** [comment]
Kamino cloned this issue to [ices-publications/SONAR-netCDF4](https://github.com/ices-publications/SONAR-netCDF4/issues/10)
