### ISSUE TITLE
Remove trailing +

### ISSUE THREAD

**Issue by cyrilleponcelet** [ices-eg/wg_WGFAST#17]
Hi gavin
Is it on purpose that we have some trailing "+" in asciidoctor file ? 
Sometimes they are in comments and most of the time in the long names. For example 
beamwidth_receive_minor 
:long_name = "Half power one-way +
receive beam width along minor +
(vertical) axis of beam" | |

I am asking this because for bathymetry I use a code generator to generate my asciidoctor files and compare them with the sonardata reference file and this '+' are quite annoying to me.

If they are here on purpose I can live with that, if not I could make a pull request to clean up the asciidoctor files

Cheers, Cyrille.

**Comment by gavinmacaulay** [comment]
I used pandoc to convert from Word to AsciiDoc and pandoc introduced them, presumably to match the line wrapping that Word had. I don't think that they are necessary, so a pull request to remove them would be nice:)

**Comment by cyrilleponcelet** [comment]
Good
Working on it

**Comment by gavinmacaulay** [comment]
Fixed in PR #18
