### ISSUE TITLE
interpretation masks

### ISSUE THREAD

**Issue by sindrevatnehol** [ices-eg/wg_WGFAST#21]
I am currently working with fisheries sonar data, that have now been converted into the netcdf format, and I have sets of interpretation masks that should be converted into a more efficient format. As different platforms/postprocessing software does this differently, I see that there is need for a common convention to store the interpretation that can be used cross platforms. I start this dialog so we can have a discussion on how to develop this further.

**Comment by gavinmacaulay** [comment]
A document that presents the different ways that acoustic analysis software stores and represents acoustic interpretation is available [here](https://docs.google.com/document/d/1F5ub9-ElnGWgoFzOhwrNiAB6fZRhKI8Nw6FskMhzI0g/edit?usp=sharing).

**Comment by nilsolav** [comment]
Have anyone thought about how to implement this? We are eager to start and if anyone wants to join, please let us know. Perhaps we could start with a test implementations of "school boxes"? We can read LSSS schoolboxes from the matlab code found here https://github.com/nilsolav/LSSSreader , and we ned a way to store these to the netCDF. Echoview "boxes" should be exactly the same.

**Comment by nilsolav** [comment]
This repository holds proposal for interpretation masks written by Gavin: https://github.com/nilsolav/EchosounderNetCDF It also has a draft code from Sindre that reads the LSSS work files. These should be merged into the convention.
