### ISSUE TITLE
On the use of groups and the need for example data

### ISSUE THREAD

**Issue by nilsolav** [ices-eg/wg_WGFAST#30]
Hi, here are a few comments from Kim @ saildrone.

Hi Nils Olav,

After reviewing internally, we had a couple of questions and comments on the format and contents of the repo:

•	Would it be possible to see an example or two of output files (and the corresponding source file)? This would be helpful to understand how any vendor-specific inputs affect the ultimate file, and how some of the spec described in the docs relates to source files (e.g. seems like there is support for multiple time dimensions -- is that for multiple sensors, multiple platforms, multiple time readings, etc.).
•	It seems like groups are being used a lot in the netCDF4 output. When we were implementing netCDF for physical oceanography variables initially, we got feedback from users not to use groups, so it's interesting to see it being relied on so heavily here. Is there a particular reason behind that?
•	If we were to implement this conversion, we'd do it in Python rather than MATLAB, but that should not affect the actual output itself.

Please let me know if it'd be helpful to discuss any of this on a call.

Thank you,
Kim

**Comment by gavinmacaulay** [comment]
Replying to the query about the use of groups - the main reason was that it was difficult to achieve the desired flexibility and generality to store different types of active backscatter data without using the organisational structure offered by groups. In addition, the users that helped develop this data structure did not have any great concerns with groups. Hence we decided that the advantages of groups out-weighed the disadvantages.
